apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: co-scraper
spec:
  ports:
    - port: 5672
      name: rabbitmq
      targetPort: 5672
    - port: 15672
      name: rabbitmq-management
      targetPort: 15672
  selector:
    app: rabbitmq