apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-product-service
  namespace: co-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-product-service
  template:
    metadata:
      labels:
        app: customer-product-service
    spec:
      containers:
        - name: customer-product-service
          image: acrcoscraper.azurecr.io/customer-product-service:dda24f097f0dcf05b09ee2bcb18eb494a3d877c7
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/customer_product
            - name: SPRING_DATASOURCE_USERNAME
              value: co-scraper
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_USERNAME
              value: coscraper
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: auth0-domain
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: auth0-clientId
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: auth0-clientSecret
      imagePullSecrets:
        - name: acr-secret