apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-product-service
  namespace: co-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-product-service
  template:
    metadata:
      labels:
        app: customer-product-service
    spec:
      containers:
        - name: customer-product-service
          image: coscraper.azurecr.io/customer-product-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/customer_product
            - name: SPRING_DATASOURCE_USERNAME
              value: co-scraper
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_USERNAME
              value: coscraper
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
      imagePullSecrets:
        - name: acr-secret