apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: co-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: acrcoscraper.azurecr.io/product-service:93797e60ea42f712c8150e739cc61f06044c37a8
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/product
            - name: SPRING_DATASOURCE_USERNAME
              value: co-scraper
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_USERNAME
              value: coscraper
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
      imagePullSecrets:
        - name: acr-secret
