apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/definitions.json
              subPath: rabbitmq-setup.json
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "coscraper"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: "/etc/rabbitmq/definitions.json"
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config