server:
  port: 8081
  servlet:
    context-path: /customer

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: 'co-scraper'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    customer_queue: 'customerQueue'
    customer_exchange: 'customerExchange'

  secret: CqBN7umAngTj1dME7HksqD3gqxiHR5AMNQJ3wfdr7WU=

okta:
  oauth2:
    issuer: https://dev-4uuuq0lgb8apygr7.us.auth0.com/
    audience: https://co-scraper-api.com
    groupsClaim: permissions
