apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq-setup.json: |
    {
      "rabbit_version": "3.8.9",
      "definitions": {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "queues": [
          {
            "name": "productQueue",
            "vhost": "/",
            "durable": true
          },
          {
            "name": "customerQueue",
            "vhost": "/",
            "durable": true
          },
          {
            "name": "customerProductQueue",
            "vhost": "/",
            "durable": true
          }
        ],
        "exchanges": [
          {
            "name": "productExchange",
            "vhost": "/",
            "type": "direct",
            "durable": true
          },
          {
            "name": "customerExchange",
            "vhost": "/",
            "type": "direct",
            "durable": true
          },
          {
            "name": "customerProductExchange",
            "vhost": "/",
            "type": "direct",
            "durable": true
          }
        ],
        "bindings": [
          {
            "source": "productExchange",
            "vhost": "/",
            "destination": "productQueue",
            "destination_type": "queue",
            "routing_key": "product.deleted",
            "arguments": {}
          },
          {
            "source": "customerExchange",
            "vhost": "/",
            "destination": "customerQueue",
            "destination_type": "queue",
            "routing_key": "customer.deleted",
            "arguments": {}
          },
          {
            "source": "customerProductExchange",
            "vhost": "/",
            "destination": "customerProductQueue",
            "destination_type": "queue",
            "routing_key": "customerProduct.deleted",
            "arguments": {}
          }
        ]
      }
    }
