server:
  port: 8082

spring:
  application:
    name: customer-product
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_product
    username: 'co-scraper'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    product_delete_queue: 'productDeleteQueue'
    customer_delete_queue: 'customerQueue'