server:
  port: 8082
  servlet:
    context-path: /customer-product

spring:
  application:
    name: customer-product
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_product
    username: 'co-scraper'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    product_delete_queue: 'productDeleteQueue'
    customer_delete_queue: 'customerQueue'

  secret: CqBN7umAngTj1dME7HksqD3gqxiHR5AMNQJ3wfdr7WU=

okta:
  oauth2:
    issuer: ${AUTH0_DOMAIN}
    audience: https://co-scraper-api.com
    groupsClaim: permissions
    client-secret: ${AUTH0_CLIENT_SECRET}
    client-id: ${AUTH0_CLIENT_ID}
