server:
  port: 8082
  servlet:
    context-path: /customer-product

spring:
  application:
    name: customer-product
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_product
    username: 'co-scraper'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    product_delete_queue: 'productDeleteQueue'
    customer_delete_queue: 'customerQueue'

okta:
  oauth2:
    issuer: https://dev-4uuuq0lgb8apygr7.us.auth0.com/
    audience: https://co-scraper-api.com
    groupsClaim: permissions
