server:
  port: 8080
  servlet:
    context-path: /product

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: 'co-scraper'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    queue_product_create: 'productCreateQueue'
    queue_product_update: 'productUpdateQueue'
    queue_product_delete: 'productDeleteQueue'
    product_exchange: 'productExchange'

  secret: CqBN7umAngTj1dME7HksqD3gqxiHR5AMNQJ3wfdr7WU=

okta:
  oauth2:
    issuer: ${AUTH0_DOMAIN}
    audience: https://co-scraper-api.com
    groupsClaim: permissions
    client-secret: ${AUTH0_CLIENT_SECRET}
    client-id: ${AUTH0_CLIENT_ID}