server:
  port: 8080

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: 'co-scraper'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    queue_product_create: 'productCreateQueue'
    queue_product_update: 'productUpdateQueue'
    queue_product_delete: 'productDeleteQueue'
    product_exchange: 'productExchange'

