apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq-setup.json: |
    {
      "rabbit_version": "3.8.9",
      "definitions": {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "queues": [
          {
            "name": "productQueue",
            "vhost": "/",
            "durable": true
          },
          {
            "name": "customerQueue",
            "vhost": "/",
            "durable": true
          },
          {
            "name": "customerProductQueue",
            "vhost": "/",
            "durable": true
          }
        ],
        "exchanges": [
          {
            "name": "productExchange",
            "vhost": "/",
            "type": "direct",
            "durable": true
          },
          {
            "name": "customerExchange",
            "vhost": "/",
            "type": "direct",
            "durable": true
          },
          {
            "name": "customerProductExchange",
            "vhost": "/",
            "type": "direct",
            "durable": true
          }
        ],
        "bindings": [
          {
            "source": "productExchange",
            "vhost": "/",
            "destination": "productQueue",
            "destination_type": "queue",
            "routing_key": "product.deleted",
            "arguments": {}
          },
          {
            "source": "customerExchange",
            "vhost": "/",
            "destination": "customerQueue",
            "destination_type": "queue",
            "routing_key": "customer.deleted",
            "arguments": {}
          },
          {
            "source": "customerProductExchange",
            "vhost": "/",
            "destination": "customerProductQueue",
            "destination_type": "queue",
            "routing_key": "customerProduct.deleted",
            "arguments": {}
          }
        ]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/definitions.json
              subPath: rabbitmq-setup.json
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "coscraper"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: "/etc/rabbitmq/definitions.json"
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672
      name: rabbitmq
      targetPort: 5672
    - port: 15672
      name: rabbitmq-management
      targetPort: 15672
  selector:
    app: rabbitmq
