apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-storage
provisioner: dobs.csi.digitalocean.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-storage