apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: co-scraper
  namespace: co-scraper
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Set to "true" if you have SSL configured
    nginx.ingress.kubernetes.io/use-regex: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 8080
          - path: /customer
            pathType: Prefix
            backend:
              service:
                name: customer-service
                port:
                  number: 8081
          - path: /customer-product
            pathType: Prefix
            backend:
              service:
                name: customer-product-service
                port:
                  number: 8082
          - path: /store
            pathType: Prefix
            backend:
              service:
                name: customer-product-service
                port:
                  number: 8082
