server:
  port: 8083
  servlet:
    context-path: /store

spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: 'co-scraper'
    password: 'password'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    product_exchange: 'productExchange'

okta:
  oauth2:
    issuer: https://dev-4uuuq0lgb8apygr7.us.auth0.com/
    audience: https://co-scraper-api.com
    groupsClaim: permissions