server:
  port: 8083

spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: 'co-scraper'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    product_exchange: 'productExchange'

