server:
  port: 8083
  servlet:
    context-path: /store

spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: 'co-scraper'
    password: 'password'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    username: 'coscraper'
    password: 'password'
    product_exchange: 'productExchange'

  secret: CqBN7umAngTj1dME7HksqD3gqxiHR5AMNQJ3wfdr7WU=

okta:
  oauth2:
    issuer: ${AUTH0_DOMAIN}
    audience: https://co-scraper-api.com
    groupsClaim: permissions
    client-secret: ${AUTH0_CLIENT_SECRET}
    client-id: ${AUTH0_CLIENT_ID}