name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy_to_kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group co-scraper --name co-scraper

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set Image Tags
        id: vars
        run: echo "::set-output name=tag::${GITHUB_SHA}"

      - name: Update Kubernetes Manifests
        run: |
          TAG=${{ steps.vars.outputs.tag }}
          sed -i "s|image: coscraper.azurecr.io/customer-service:.*|image: coscraper.azurecr.io/customer-service:$TAG|" k8s-configs/deployments/customer-deployment.yaml
          sed -i "s|image: coscraper.azurecr.io/product-service:.*|image: coscraper.azurecr.io/product-service:$TAG|" k8s-configs/deployments/product-deployment.yaml
          sed -i "s|image: coscraper.azurecr.io/customer-product-service:.*|image: coscraper.azurecr.io/customer-product-service:$TAG|" k8s-configs/deployments/customer-product-deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          for file in k8s-configs/deployments/*.yaml; do
            kubectl apply -f "$file"
          done
          for file in k8s-configs/config-maps/*.yaml; do
            kubectl apply -f "$file"
          done
          for file in k8s-configs/network-policies/*.yaml; do
            kubectl apply -f "$file"
          done
          for file in k8s-configs/services/*.yaml; do
            kubectl apply -f "$file"
          done
          kubectl apply -f k8s-configs/hpa-services.yaml
          kubectl apply -f k8s-configs/ingress.yaml
          kubectl apply -f k8s-configs/ingress-controller.yaml
