name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - customer-service
          - product-service
          - customer-product-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          mvn clean install

      - name: Build Docker image and push to registry for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ secrets.AZURE_REGISTRY }}.azurecr.io/${{ matrix.service }}:${{ github.sha }} .
          docker login ${{ secrets.AZURE_REGISTRY }}.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          docker push ${{ secrets.AZURE_REGISTRY }}.azurecr.io/${{ matrix.service }}:${{ github.sha }}
