name: Docker Build And Push

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Build Docker images
        run: |
          docker build -t customer-service:latest -f customer-service/Dockerfile .
          docker build -t product-service:latest -f product-service/Dockerfile .
          docker build -t customer-product-service:latest -f customer-product-service/Dockerfile .

      - name: Log in to Azure Container Registry
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Tag and push Docker images to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.AZURE_REGISTRY }}
          
          docker tag customer-service:latest ${{ secrets.AZURE_REGISTRY }}.azurecr.io/customer-service:latest
          docker tag product-service:latest ${{ secrets.AZURE_REGISTRY }}.azurecr.io/product-service:latest
          docker tag customer-product-service:latest ${{ secrets.AZURE_REGISTRY }}.azurecr.io/customer-product-service:latest
          
          docker push ${{ secrets.AZURE_REGISTRY }}.azurecr.io/customer-service:latest
          docker push ${{ secrets.AZURE_REGISTRY }}.azurecr.io/product-service:latest
          docker push ${{ secrets.AZURE_REGISTRY }}.azurecr.io/customer-product-service:latest
