name: Docker Build And Push

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          
          cd customer-service
          docker build -t customer-service:$COMMIT_SHA -f Dockerfile .
          cd ../product-service
          docker build -t product-service:$COMMIT_SHA -f Dockerfile .
          cd ../customer-product-service
          docker build -t customer-product-service:$COMMIT_SHA -f Dockerfile .

      - name: Log in to Azure Container Registry
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Tag and push Docker images to Azure Container Registry
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          az acr login --name ${{ secrets.AZURE_REGISTRY }}
          
          docker tag customer-service:$COMMIT_SHA ${{ secrets.AZURE_REGISTRY }}.azurecr.io/customer-service:$COMMIT_SHA
          docker tag product-service:$COMMIT_SHA ${{ secrets.AZURE_REGISTRY }}.azurecr.io/product-service:$COMMIT_SHA
          docker tag customer-product-service:$COMMIT_SHA ${{ secrets.AZURE_REGISTRY }}.azurecr.io/customer-product-service:$COMMIT_SHA
          
          docker push ${{ secrets.AZURE_REGISTRY }}.azurecr.io/customer-service:$COMMIT_SHA
          docker push ${{ secrets.AZURE_REGISTRY }}.azurecr.io/product-service:$COMMIT_SHA
          docker push ${{ secrets.AZURE_REGISTRY }}.azurecr.io/customer-product-service:$COMMIT_SHA

      - name: Set output tag
        id: vars
        run: echo "::set-output name=tag::$COMMIT_SHA"
